// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                    = new(Query)
	OtaUpgradePackage    *otaUpgradePackage
	OtaUpgradeTask       *otaUpgradeTask
	OtaUpgradeTaskDetail *otaUpgradeTaskDetail
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	OtaUpgradePackage = &Q.OtaUpgradePackage
	OtaUpgradeTask = &Q.OtaUpgradeTask
	OtaUpgradeTaskDetail = &Q.OtaUpgradeTaskDetail
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                   db,
		OtaUpgradePackage:    newOtaUpgradePackage(db, opts...),
		OtaUpgradeTask:       newOtaUpgradeTask(db, opts...),
		OtaUpgradeTaskDetail: newOtaUpgradeTaskDetail(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	OtaUpgradePackage    otaUpgradePackage
	OtaUpgradeTask       otaUpgradeTask
	OtaUpgradeTaskDetail otaUpgradeTaskDetail
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		OtaUpgradePackage:    q.OtaUpgradePackage.clone(db),
		OtaUpgradeTask:       q.OtaUpgradeTask.clone(db),
		OtaUpgradeTaskDetail: q.OtaUpgradeTaskDetail.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                   db,
		OtaUpgradePackage:    q.OtaUpgradePackage.replaceDB(db),
		OtaUpgradeTask:       q.OtaUpgradeTask.replaceDB(db),
		OtaUpgradeTaskDetail: q.OtaUpgradeTaskDetail.replaceDB(db),
	}
}

type queryCtx struct {
	OtaUpgradePackage    IOtaUpgradePackageDo
	OtaUpgradeTask       IOtaUpgradeTaskDo
	OtaUpgradeTaskDetail IOtaUpgradeTaskDetailDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		OtaUpgradePackage:    q.OtaUpgradePackage.WithContext(ctx),
		OtaUpgradeTask:       q.OtaUpgradeTask.WithContext(ctx),
		OtaUpgradeTaskDetail: q.OtaUpgradeTaskDetail.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
